import { el, setHidden } from "./dom.js";
import { getPmeSettings, patchPmeSettings } from "../../store/personaStore.js";

const WRAPPER_PLACEHOLDER = "{{PROMPT}}";
const WRAPPER_TEXTAREA_ID = "pme_settings_wrapper_template";

export function createSettingsCard() {
  let collapsed = true;

  const root = el("div", "pme-card pme-settings-card");
  const header = el("div", "pme-card-title-row");
  header.appendChild(el("div", "pme-card-title", "Settings"));

  const actions = el("div", "pme-actions");
  const collapseBtn = el("button", "menu_button menu_button_icon pme-icon-btn");
  collapseBtn.type = "button";
  actions.appendChild(collapseBtn);
  header.appendChild(actions);
  root.appendChild(header);

  const body = el("div", "pme-settings-body");
  root.appendChild(body);

  // Wrapper block
  const wrapperRow = el("div", "pme-settings-row");
  const wrapperTitleRow = el("div", "pme-settings-title-row");
  wrapperTitleRow.appendChild(el("div", "pme-settings-label", "Wrapper"));

  const wrapperControls = el("div", "pme-settings-controls");
  const wrapperToggleLabel = el(
    "label",
    "checkbox_label pme-settings-checkbox"
  );
  const wrapperToggle = el("input");
  wrapperToggle.type = "checkbox";
  wrapperToggleLabel.appendChild(wrapperToggle);
  wrapperToggleLabel.appendChild(el("span", "", "Enabled"));
  wrapperTitleRow.appendChild(wrapperToggleLabel);
  wrapperRow.appendChild(wrapperTitleRow);

  const wrapperTextarea = document.createElement("textarea");
  wrapperTextarea.id = WRAPPER_TEXTAREA_ID;
  wrapperTextarea.className =
    "text_pole textarea_compact pme-settings-textarea";
  wrapperTextarea.rows = 4;
  wrapperTextarea.placeholder = `<tag>${WRAPPER_PLACEHOLDER}</tag>`;
  wrapperControls.appendChild(wrapperTextarea);

  const wrapperFooter = el("div", "pme-settings-footer");
  const wrapperMaxBtn = document.createElement("i");
  wrapperMaxBtn.className =
    "editor_maximize fa-solid fa-maximize right_menu_button";
  wrapperMaxBtn.title = "Expand the editor";
  wrapperMaxBtn.setAttribute("data-for", WRAPPER_TEXTAREA_ID);
  wrapperFooter.appendChild(wrapperMaxBtn);
  wrapperControls.appendChild(wrapperFooter);

  wrapperRow.appendChild(wrapperControls);
  body.appendChild(wrapperRow);

  const wrapperHelp = el(
    "div",
    "text_muted pme-settings-help",
    `When enabled, the final persona prompt generated by PME will be inserted into this template by replacing ${WRAPPER_PLACEHOLDER}.`
  );
  body.appendChild(wrapperHelp);

  // Joiner block
  body.appendChild(el("hr", "sysHR"));

  const joinerRow = el("div", "pme-settings-row");
  joinerRow.appendChild(
    el("div", "pme-settings-label", "Additional Descriptions joiner")
  );

  const joinerControls = el("div", "pme-settings-controls");
  const joinerInput = el("input", "text_pole pme-settings-input");
  joinerInput.type = "text";
  joinerInput.placeholder = "\\n\\n";
  joinerControls.appendChild(joinerInput);
  joinerRow.appendChild(joinerControls);
  body.appendChild(joinerRow);

  const joinerHelp = el(
    "div",
    "text_muted pme-settings-help",
    "String used to join enabled Additional Descriptions blocks. Supports escape sequences like \\n, \\t, \\r, and \\\\."
  );
  body.appendChild(joinerHelp);

  function syncCollapsedUI() {
    collapseBtn.title = collapsed ? "Expand" : "Collapse";
    collapseBtn.innerHTML = collapsed
      ? '<i class="fa-solid fa-chevron-down"></i>'
      : '<i class="fa-solid fa-chevron-up"></i>';
    setHidden(body, collapsed);
    root.classList.toggle("pme-collapsed", collapsed);
  }

  collapseBtn.addEventListener("click", (e) => {
    e.preventDefault();
    e.stopPropagation();
    collapsed = !collapsed;
    syncCollapsedUI();
  });

  wrapperToggle.addEventListener("input", () => {
    patchPmeSettings({ wrapperEnabled: wrapperToggle.checked });
  });

  wrapperTextarea.addEventListener("input", () => {
    patchPmeSettings({ wrapperTemplate: String(wrapperTextarea.value ?? "") });
  });
  try {
    // ST "Expand editor" uses jQuery `.trigger('input')` on the original element.
    // Native listener is not guaranteed to receive that trigger, so we bind both.
    // eslint-disable-next-line no-undef
    if (typeof $ === "function")
      $(wrapperTextarea).on("input", () => {
        patchPmeSettings({
          wrapperTemplate: String(wrapperTextarea.value ?? ""),
        });
      });
  } catch {
    // ignore
  }

  joinerInput.addEventListener("input", () => {
    patchPmeSettings({ additionalJoiner: String(joinerInput.value ?? "") });
  });

  function render() {
    const s = getPmeSettings();
    wrapperToggle.checked = s?.wrapperEnabled === true;
    wrapperTextarea.value = String(s?.wrapperTemplate ?? "");
    joinerInput.value = String(s?.additionalJoiner ?? "\\n\\n");
  }

  return {
    el: root,
    mount() {
      render();
      syncCollapsedUI();
    },
    update() {
      render();
      syncCollapsedUI();
    },
  };
}
